### ISSUE TITLE
not working in background

### ISSUE THREAD

**Issue by treakiandroid** [ligi/MaterialTeaTimer#4]
timer stops when the activity goes to backround, there by its useless. please fix that with a good working Android service that won't even stop countong under high load.

Thanks

**Comment by ligi** [comment]
hm strange - I am using AlarmManager which should not be killed and did not do so in my tests. The only time it should stop is when you kill the app by your self - but IMHO then the behavior is correct. Can you tell me how you tested?

**Comment by ligi** [comment]
closing as I cannot reproduce and this issue is missing details. Feel free to reopen with more information
