### ISSUE TITLE
Abandoned project ?

### ISSUE THREAD

**Issue by aha999** [ligi/MaterialTeaTimer#58]
I really like your app's potential as it's curently my favourite open source tea timer app, but it's missing some important features and i haven't seen any development in a while. Is the project abandoned ?

**Comment by ligi** [comment]
Actually I have some plans for it - unfortunately did not yet find the time. What changed do you want to see? Ideally open this as new issues - need to close this one as it is not that actionable ;-)

**Comment by aha999** [comment]
That sounds great! well i already have 9 issues open, but the most important one in my opinion would be #11, so we could add custom tea timers

**Comment by CodingInSecret** [comment]
Well, since it's been 4 years, i'm guessing this is abandoned.
