### ISSUE TITLE
[Suggestion] Small (probably) redesign

### ISSUE THREAD

**Issue by homocomputeris** [ligi/MaterialTeaTimer#6]
Hi,
I suggest this new layout:
* to save taps: 1 to start and 1 to stop instead of 2 to start and 2 to stop and reset;
* to run two or more timers at once.
![newdesign](https://cloud.githubusercontent.com/assets/7422433/21299414/b252749c-c59b-11e6-907e-6434ac432954.png)

Tapping is especially annoying.

**Comment by ligi** [comment]
Thanks but I will not do this - Usually it is only one tap - only 2 if you want to make a different tea from before. Also I want to grow the list of teas - then it get's annoying to select the tea.
That said - the app is free software - so you can fork and make the changes
